services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=transcription-v2'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data: